package repository

import (
	"context"
	"errors"
	"time"
)

// ErrLanguageAlreadySet is returned when a student who already has a
// language track tries to self-declare a different one — the field is
// set once (self-declared for now, director/teacher-assigned from
// Phase 4 on) and then locked.
var ErrLanguageAlreadySet = errors.New("language already set")

type StudentSummary struct {
	ID                    string    `json:"id"`
	FullName              string    `json:"full_name"`
	Level                 string    `json:"level"`
	Language              *string   `json:"language,omitempty"` // "en" | "zh" | nil (prodlenka/mad)
	StreakDays            int       `json:"streak_days"`
	Balance               float64   `json:"balance"`
	PaymentStatus         string    `json:"payment_status"`
	SubscriptionExpiresAt time.Time `json:"subscription_expires_at"`
}

type StudentRepo struct{ store *Store }

func NewStudentRepo(s *Store) *StudentRepo { return &StudentRepo{store: s} }

// CreateFromLead auto-provisions a student profile the moment a lead
// reaches the "paid" Kanban stage (the CRM->LMS funnel). loginCode and
// passwordHash are generated by the caller (handler), since credential
// generation/hashing is auth's responsibility, not the repo's.
func (r *StudentRepo) CreateFromLead(ctx context.Context, branchID, fullName, loginCode, passwordHash, level string) (string, error) {
	var id string
	err := r.store.Pool.QueryRow(ctx, `
		INSERT INTO students (branch_id, login_code, password_hash, full_name, program, level, payment_status)
		VALUES ($1, $2, $3, $4, 'language_course', $5, 'paid')
		RETURNING id
	`, branchID, loginCode, passwordHash, fullName, level).Scan(&id)
	return id, err
}

// FindIDsByParentID returns every student linked to a parent account.
// A parent's JWT carries their own ID, not a student's — every
// family-scoped read (progress, balance, report, certificates) needs
// to resolve through here first when the caller is a parent rather
// than a student.
func (r *StudentRepo) FindIDsByParentID(ctx context.Context, parentID string) ([]string, error) {
	rows, err := r.store.Pool.Query(ctx, `SELECT id FROM students WHERE parent_id = $1 ORDER BY created_at`, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

func (r *StudentRepo) GetSummary(ctx context.Context, studentID string) (*StudentSummary, error) {
	var s StudentSummary
	var expires *time.Time
	err := r.store.Pool.QueryRow(ctx, `
		SELECT id, full_name, COALESCE(level, ''), language, streak_days, balance,
		       payment_status, subscription_expires_at
		FROM students WHERE id = $1
	`, studentID).Scan(&s.ID, &s.FullName, &s.Level, &s.Language, &s.StreakDays, &s.Balance,
		&s.PaymentStatus, &expires)
	if err != nil {
		return nil, err
	}
	if expires != nil {
		s.SubscriptionExpiresAt = *expires
	}
	return &s, nil
}

// SetLanguageIfUnset assigns a student's language track exactly once —
// a bridge until Phase 4 gives directors a real enrollment-time
// assignment UI. Returns ErrLanguageAlreadySet if already assigned.
func (r *StudentRepo) SetLanguageIfUnset(ctx context.Context, studentID, language string) error {
	tag, err := r.store.Pool.Exec(ctx, `
		UPDATE students SET language = $2, updated_at = now()
		WHERE id = $1 AND language IS NULL
	`, studentID, language)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrLanguageAlreadySet
	}
	return nil
}

// ConfirmPayment is the "manual payment status" flow: a teacher marks a
// student as paid after the parent transfers money outside the platform.
func (r *StudentRepo) ConfirmPayment(ctx context.Context, studentID, confirmedByTeacherID string, amount float64, periodStart, periodEnd time.Time, method string) error {
	tx, err := r.store.Pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	var branchID string
	if err := tx.QueryRow(ctx, `SELECT branch_id FROM students WHERE id = $1`, studentID).Scan(&branchID); err != nil {
		return err
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO payments (student_id, branch_id, amount, status, confirmed_by, confirmed_at, period_start, period_end, method)
		VALUES ($1, $2, $3, 'paid', $4, now(), $5, $6, $7)
	`, studentID, branchID, amount, confirmedByTeacherID, periodStart, periodEnd, method); err != nil {
		return err
	}

	if _, err := tx.Exec(ctx, `
		UPDATE students
		SET payment_status = 'paid', subscription_expires_at = $2, updated_at = now()
		WHERE id = $1
	`, studentID, periodEnd); err != nil {
		return err
	}

	return tx.Commit(ctx)
}

// ListByBranch returns every student in a branch — the director's full
// "Оқушылар" roster (as opposed to ListOverdue, which is debtors only).
func (r *StudentRepo) ListByBranch(ctx context.Context, branchID string) ([]StudentSummary, error) {
	rows, err := r.store.Pool.Query(ctx, `
		SELECT id, full_name, COALESCE(level, ''), language, streak_days, balance, payment_status, subscription_expires_at
		FROM students
		WHERE branch_id = $1
		ORDER BY full_name
	`, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []StudentSummary
	for rows.Next() {
		var s StudentSummary
		var expires *time.Time
		if err := rows.Scan(&s.ID, &s.FullName, &s.Level, &s.Language, &s.StreakDays, &s.Balance, &s.PaymentStatus, &expires); err != nil {
			return nil, err
		}
		if expires != nil {
			s.SubscriptionExpiresAt = *expires
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// ListOverdue supports the director's "debtors" view — students whose
// subscription has lapsed.
func (r *StudentRepo) ListOverdue(ctx context.Context, branchID string) ([]StudentSummary, error) {
	rows, err := r.store.Pool.Query(ctx, `
		SELECT id, full_name, COALESCE(level, ''), streak_days, balance, payment_status, subscription_expires_at
		FROM students
		WHERE branch_id = $1
		  AND (payment_status = 'overdue' OR subscription_expires_at < CURRENT_DATE)
		ORDER BY subscription_expires_at ASC NULLS FIRST
	`, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []StudentSummary
	for rows.Next() {
		var s StudentSummary
		var expires *time.Time
		if err := rows.Scan(&s.ID, &s.FullName, &s.Level, &s.StreakDays, &s.Balance, &s.PaymentStatus, &expires); err != nil {
			return nil, err
		}
		if expires != nil {
			s.SubscriptionExpiresAt = *expires
		}
		out = append(out, s)
	}
	return out, rows.Err()
}
