package repository

import (
	"context"
	"time"
)

type StudentSummary struct {
	ID                    string    `json:"id"`
	FullName              string    `json:"full_name"`
	CourseType            string    `json:"course_type"` // "language" | "care_and_prep"
	Subject               *string   `json:"subject,omitempty"`
	Level                 string    `json:"level,omitempty"` // CEFR/HSK, empty for care_and_prep or unassigned
	StreakDays            int       `json:"streak_days"`
	Balance               float64   `json:"balance"`
	PaymentStatus         string    `json:"payment_status"`
	SubscriptionExpiresAt time.Time `json:"subscription_expires_at"`
}

type StudentRepo struct{ store *Store }

func NewStudentRepo(s *Store) *StudentRepo { return &StudentRepo{store: s} }

// CreateFromLead auto-provisions a language-course student the moment
// a lead reaches the "paid" Kanban stage (the CRM->LMS funnel).
// loginCode and passwordHash are generated by the caller (handler),
// since credential generation/hashing is auth's responsibility, not
// the repo's. level starts unassigned — set later once the student's
// placement/practice results or a teacher's assessment place them.
func (r *StudentRepo) CreateFromLead(ctx context.Context, branchID, fullName, loginCode, passwordHash, subject string) (string, error) {
	var id string
	err := r.store.Pool.QueryRow(ctx, `
		INSERT INTO students (branch_id, login_code, password_hash, full_name, program, course_type, subject, payment_status)
		VALUES ($1, $2, $3, $4, 'language_course', 'language', $5, 'paid')
		RETURNING id
	`, branchID, loginCode, passwordHash, fullName, subject).Scan(&id)
	return id, err
}

// CreateChild provisions a CARE_AND_PREP (mad/prodlenka) child — no
// login of their own; only the linked parent account can sign in.
// Created directly by a director/teacher, not via the lead pipeline
// (placement tests don't apply to this course type).
func (r *StudentRepo) CreateChild(ctx context.Context, branchID, parentID, fullName, subject string) (string, error) {
	var id string
	err := r.store.Pool.QueryRow(ctx, `
		INSERT INTO students (branch_id, parent_id, full_name, program, course_type, subject, payment_status)
		VALUES ($1, $2, $3, 'prodlenka', 'care_and_prep', $4, 'pending')
		RETURNING id
	`, branchID, parentID, fullName, subject).Scan(&id)
	return id, err
}

// FindIDsByParentID returns every student linked to a parent account.
// A parent's JWT carries their own ID, not a student's — every
// family-scoped read (progress, balance, report, certificates) needs
// to resolve through here first when the caller is a parent rather
// than a student.
func (r *StudentRepo) FindIDsByParentID(ctx context.Context, parentID string) ([]string, error) {
	rows, err := r.store.Pool.Query(ctx, `SELECT id FROM students WHERE parent_id = $1 ORDER BY created_at`, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

func (r *StudentRepo) GetSummary(ctx context.Context, studentID string) (*StudentSummary, error) {
	var s StudentSummary
	var expires *time.Time
	err := r.store.Pool.QueryRow(ctx, `
		SELECT id, full_name, course_type, subject::text, COALESCE(level::text, ''), streak_days, balance,
		       payment_status, subscription_expires_at
		FROM students WHERE id = $1
	`, studentID).Scan(&s.ID, &s.FullName, &s.CourseType, &s.Subject, &s.Level, &s.StreakDays, &s.Balance,
		&s.PaymentStatus, &expires)
	if err != nil {
		return nil, err
	}
	if expires != nil {
		s.SubscriptionExpiresAt = *expires
	}
	return &s, nil
}

// SetLevel assigns/updates a student's CEFR/HSK level — called by a
// teacher/director once a placement result or their own assessment
// places the student (level is no longer self-declared by students).
func (r *StudentRepo) SetLevel(ctx context.Context, studentID, level string) error {
	_, err := r.store.Pool.Exec(ctx, `
		UPDATE students SET level = $2, updated_at = now() WHERE id = $1
	`, studentID, level)
	return err
}

// ConfirmPayment is the "manual payment status" flow: a teacher marks a
// student as paid after the parent transfers money outside the platform.
func (r *StudentRepo) ConfirmPayment(ctx context.Context, studentID, confirmedByTeacherID string, amount float64, periodStart, periodEnd time.Time, method string) error {
	tx, err := r.store.Pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	var branchID string
	if err := tx.QueryRow(ctx, `SELECT branch_id FROM students WHERE id = $1`, studentID).Scan(&branchID); err != nil {
		return err
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO payments (student_id, branch_id, amount, status, confirmed_by, confirmed_at, period_start, period_end, method)
		VALUES ($1, $2, $3, 'paid', $4, now(), $5, $6, $7)
	`, studentID, branchID, amount, confirmedByTeacherID, periodStart, periodEnd, method); err != nil {
		return err
	}

	if _, err := tx.Exec(ctx, `
		UPDATE students
		SET payment_status = 'paid', subscription_expires_at = $2, updated_at = now()
		WHERE id = $1
	`, studentID, periodEnd); err != nil {
		return err
	}

	return tx.Commit(ctx)
}

// ListByBranch returns every student in a branch, or every branch's if
// branchID is "" (super_admin / network-owner director) — the
// director's full "Оқушылар" roster (as opposed to ListOverdue, which
// is debtors only).
func (r *StudentRepo) ListByBranch(ctx context.Context, branchID string) ([]StudentSummary, error) {
	rows, err := r.store.Pool.Query(ctx, `
		SELECT id, full_name, course_type, subject::text, COALESCE(level::text, ''), streak_days, balance, payment_status, subscription_expires_at
		FROM students
		WHERE ($1 = '' OR branch_id = $1::uuid)
		ORDER BY full_name
	`, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []StudentSummary
	for rows.Next() {
		var s StudentSummary
		var expires *time.Time
		if err := rows.Scan(&s.ID, &s.FullName, &s.CourseType, &s.Subject, &s.Level, &s.StreakDays, &s.Balance, &s.PaymentStatus, &expires); err != nil {
			return nil, err
		}
		if expires != nil {
			s.SubscriptionExpiresAt = *expires
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// ListOverdue supports the director's "debtors" view — students whose
// subscription has lapsed.
func (r *StudentRepo) ListOverdue(ctx context.Context, branchID string) ([]StudentSummary, error) {
	rows, err := r.store.Pool.Query(ctx, `
		SELECT id, full_name, course_type, subject::text, COALESCE(level::text, ''), streak_days, balance, payment_status, subscription_expires_at
		FROM students
		WHERE ($1 = '' OR branch_id = $1::uuid)
		  AND (payment_status = 'overdue' OR subscription_expires_at < CURRENT_DATE)
		ORDER BY subscription_expires_at ASC NULLS FIRST
	`, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []StudentSummary
	for rows.Next() {
		var s StudentSummary
		var expires *time.Time
		if err := rows.Scan(&s.ID, &s.FullName, &s.CourseType, &s.Subject, &s.Level, &s.StreakDays, &s.Balance, &s.PaymentStatus, &expires); err != nil {
			return nil, err
		}
		if expires != nil {
			s.SubscriptionExpiresAt = *expires
		}
		out = append(out, s)
	}
	return out, rows.Err()
}
