// Package main is the dosedu.kz API entrypoint.
//
// @title						dosedu.kz LMS API
// @version					1.0
// @description				Тіл курстары мен продленка орталықтарын басқаруға арналған SaaS платформасының REST API құжаттамасы.
// @description				Rate limits, auth flow, and role-specific endpoints are grouped by subdomain (s-admin/director/teacher/family).
// @contact.name				DOS EDUCATION
// @contact.url				https://dosedu.kz
// @license.name				Proprietary
// @host						localhost:8080
// @BasePath					/
// @securityDefinitions.apikey	BearerAuth
// @in							header
// @name						Authorization
// @description				Type "Bearer" followed by a space and the JWT, e.g. "Bearer eyJhbGc..."
package main

import (
	"context"
	"log/slog"
	"os"

	"github.com/redis/go-redis/v9"

	_ "github.com/dosedu/lms/docs" // generated by `swag init` — see Dockerfile
	"github.com/dosedu/lms/internal/ai"
	"github.com/dosedu/lms/internal/auth"
	"github.com/dosedu/lms/internal/config"
	"github.com/dosedu/lms/internal/handlers"
	"github.com/dosedu/lms/internal/ratelimit"
	"github.com/dosedu/lms/internal/repository"
	"github.com/dosedu/lms/internal/telegram"
)

func main() {
	cfg := config.Load()

	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	rdb := redis.NewClient(&redis.Options{
		Addr:     cfg.RedisAddr,
		Password: cfg.RedisPassword,
	})
	if err := rdb.Ping(context.Background()).Err(); err != nil {
		logger.Error("redis connection failed", "error", err)
		os.Exit(1)
	}

	store, err := repository.NewStore(context.Background(), cfg.PostgresDSN)
	if err != nil {
		logger.Error("postgres connection failed", "error", err)
		os.Exit(1)
	}
	defer store.Close()

	sm := auth.NewSessionManager(rdb, cfg.JWTSecret, cfg.SessionTTL)

	parentRepo := repository.NewParentRepo(store)
	tgClient := telegram.NewClient(cfg.TelegramBotToken)
	notifier := telegram.NewNotifier(tgClient)
	tgHook := telegram.NewWebhookHandler(tgClient, handlers.NewParentAdapter(parentRepo), handlers.NewParentAdapter(parentRepo))

	deps := &handlers.Deps{
		Sessions:              sm,
		Creds:                 repository.NewCredentialRepo(store),
		Leads:                 repository.NewLeadRepo(store),
		Students:              repository.NewStudentRepo(store),
		Schedule:              repository.NewScheduleRepo(store),
		Parents:               parentRepo,
		Attendance:            repository.NewAttendanceRepo(store),
		TelegramBot:           tgClient,
		Notify:                notifier,
		TelegramHook:          tgHook,
		TelegramWebhookSecret: cfg.TelegramWebhookSecret,
		Certificates:          repository.NewCertificateRepo(store),
		Tickets:               repository.NewTicketRepo(store),
		Branches:              repository.NewBranchRepo(store),
		AdminDirectors:        repository.NewAdminDirectorRepo(store),
		SystemLogs:            repository.NewSystemLogRepo(store),
		Questions:             repository.NewQuestionRepo(store),
		TestAssignments:       repository.NewTestAssignmentRepo(store),
		DailyLogs:             repository.NewDailyLogRepo(store),
		Impersonation:         repository.NewImpersonationRepo(store),
		ChurnAlerts:           repository.NewChurnAlertRepo(store),
		TestUploads:           repository.NewTestUploadRepo(store),
		Payments:              repository.NewPaymentRepo(store),
		AI:                    ai.NewClient(cfg.AnthropicAPIKey),
		Redis:                 rdb,
		RateLimit:             ratelimit.New(rdb),
		MainSiteURL:           cfg.MainSiteURL,
		AppSiteURL:            cfg.AppSiteURL,
		TeacherSiteURL:        cfg.TeacherSiteURL,
		DirectorSiteURL:       cfg.DirectorSiteURL,
		AdminSiteURL:          cfg.AdminSiteURL,
	}

	router := handlers.SetupRouter(deps)

	logger.Info("dosedu.kz API starting", "port", cfg.HTTPPort, "env", cfg.Env)
	if err := router.Run(":" + cfg.HTTPPort); err != nil {
		logger.Error("server stopped", "error", err)
		os.Exit(1)
	}
}
