-- dosedu.kz LMS — initial schema
-- PostgreSQL 15+

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "btree_gist"; -- needed for the room-overlap EXCLUDE constraint

-- ============================================================
-- ENUM TYPES
-- ============================================================
CREATE TYPE branch_status AS ENUM ('active', 'blocked');
CREATE TYPE lead_stage AS ENUM ('new', 'contacted', 'trial_scheduled', 'paid', 'lost');
CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'overdue');
CREATE TYPE attendance_status AS ENUM ('present', 'absent', 'excused');
CREATE TYPE test_upload_status AS ENUM ('processing', 'ok', 'failed');
CREATE TYPE program_type AS ENUM ('language_course', 'prodlenka');

-- ============================================================
-- CORE TENANCY
-- ============================================================
CREATE TABLE branches (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            VARCHAR(255) NOT NULL,
    address         TEXT,
    status          branch_status NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- USERS (each role gets its own table -> different password
-- policy, different subdomain login, different session TTL)
-- ============================================================

-- Super Admin: exactly 10-char complex password, global scope, incognito use
CREATE TABLE super_admins (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL, -- bcrypt
    full_name       VARCHAR(255),
    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Director: exactly 8-char complex password, scoped to one branch
CREATE TABLE directors (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL, -- bcrypt, generated by super admin
    full_name       VARCHAR(255),
    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Teacher: min 6 chars, letters+digits, scoped to one branch
CREATE TABLE teachers (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL, -- bcrypt, set by director
    full_name       VARCHAR(255) NOT NULL,
    subject         VARCHAR(255),          -- responsible subject / cabinet
    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Parent: exactly 4-digit numeric PIN
CREATE TABLE parents (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    phone           VARCHAR(32) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL, -- bcrypt of 4-digit PIN
    full_name       VARCHAR(255),
    telegram_chat_id VARCHAR(64),          -- for bot / mini app notifications
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Student: exactly 4-digit numeric PIN
CREATE TABLE students (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    parent_id       UUID REFERENCES parents(id) ON DELETE SET NULL,
    login_code      VARCHAR(32) UNIQUE NOT NULL, -- e.g. short student login
    password_hash   VARCHAR(255) NOT NULL,       -- bcrypt of 4-digit PIN
    full_name       VARCHAR(255) NOT NULL,
    program         program_type NOT NULL,
    level           VARCHAR(64),                 -- e.g. Beginner, HSK1
    streak_days     INTEGER NOT NULL DEFAULT 0,
    balance         NUMERIC(12,2) NOT NULL DEFAULT 0,
    payment_status  payment_status NOT NULL DEFAULT 'pending',
    subscription_expires_at DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_students_branch ON students(branch_id);
CREATE INDEX idx_students_parent ON students(parent_id);

-- ============================================================
-- CRM / LEADS (from public landing page dosedu.kz)
-- ============================================================
CREATE TABLE leads (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id       UUID REFERENCES branches(id) ON DELETE SET NULL,
    full_name       VARCHAR(255) NOT NULL,
    phone           VARCHAR(32) NOT NULL,
    level_test_result VARCHAR(64),
    stage           lead_stage NOT NULL DEFAULT 'new',
    assigned_to     UUID REFERENCES directors(id),
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_leads_branch_stage ON leads(branch_id, stage);

-- ============================================================
-- PAYMENTS
-- ============================================================
CREATE TABLE payments (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id      UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    amount          NUMERIC(12,2) NOT NULL,
    status          payment_status NOT NULL DEFAULT 'pending',
    confirmed_by    UUID, -- teacher_id or director_id (manual confirmation)
    confirmed_at    TIMESTAMPTZ,
    period_start    DATE,
    period_end      DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_student ON payments(student_id);

-- ============================================================
-- SCHEDULE / ROOMS / CONFLICT CHECK
-- ============================================================
CREATE TABLE rooms (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    name            VARCHAR(64) NOT NULL
);

CREATE TABLE groups (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    teacher_id      UUID REFERENCES teachers(id),
    program         program_type NOT NULL,
    level           VARCHAR(64),
    name            VARCHAR(255) NOT NULL
);

CREATE TABLE group_students (
    group_id        UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    student_id      UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, student_id)
);

CREATE TABLE schedule_slots (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    group_id        UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    teacher_id      UUID NOT NULL REFERENCES teachers(id),
    room_id         UUID NOT NULL REFERENCES rooms(id),
    weekday         SMALLINT NOT NULL CHECK (weekday BETWEEN 1 AND 7),
    start_time      TIME NOT NULL,
    end_time        TIME NOT NULL,
    -- prevents double-booking the same room at overlapping times
    CONSTRAINT no_room_overlap EXCLUDE USING gist (
        room_id WITH =,
        weekday WITH =,
        tsrange('2000-01-01'::date + start_time, '2000-01-01'::date + end_time) WITH &&
    )
);

-- ============================================================
-- ATTENDANCE / GRADEBOOK / QR
-- ============================================================
CREATE TABLE attendance (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id      UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    schedule_slot_id UUID REFERENCES schedule_slots(id),
    lesson_date     DATE NOT NULL,
    status          attendance_status NOT NULL,
    grade           NUMERIC(5,2),
    marked_by       UUID NOT NULL, -- teacher_id
    qr_checked_in_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_attendance_student_date ON attendance(student_id, lesson_date);
CREATE UNIQUE INDEX uq_attendance_student_day ON attendance(student_id, lesson_date);

-- ============================================================
-- LEVEL TESTS (teacher upload panel, error-log validated)
-- ============================================================
CREATE TABLE test_uploads (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_id       UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    teacher_id      UUID NOT NULL REFERENCES teachers(id),
    level           VARCHAR(64) NOT NULL,
    file_name       VARCHAR(255) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    status          test_upload_status NOT NULL DEFAULT 'processing',
    error_log       JSONB,             -- [{row: 12, message: "..."}]
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- SYSTEM LOGS / SECURITY ALERTS (super admin panel)
-- ============================================================
CREATE TABLE system_logs (
    id              BIGSERIAL PRIMARY KEY,
    level           VARCHAR(16) NOT NULL, -- info | warn | error | security
    source          VARCHAR(128) NOT NULL,
    message         TEXT NOT NULL,
    meta            JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_system_logs_level_time ON system_logs(level, created_at DESC);

-- ============================================================
-- TRANSFER HISTORY (branch-to-branch student move)
-- ============================================================
CREATE TABLE branch_transfers (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id      UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    from_branch_id  UUID REFERENCES branches(id),
    to_branch_id    UUID REFERENCES branches(id),
    balance_carried NUMERIC(12,2) NOT NULL DEFAULT 0,
    transferred_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- updated_at auto-touch trigger
-- ============================================================
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_branches_updated BEFORE UPDATE ON branches
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_students_updated BEFORE UPDATE ON students
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_leads_updated BEFORE UPDATE ON leads
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
